### PR TITLE
container.security context.privileged boolean

### PR DESCRIPTION
**Pull request by Tacklebox**
My previous PR had the wrong type name.

bool -> boolean

### CODE REVIEW

**Review by kgeller — COMMENTED** [review]
@Tacklebox thanks for fixing this!

Would you just add this PR to the changelog ie

`* Added `container.privileged` to indicated whether a container was started in privileged mode. #2219, #2246`

**Review by ruflin — APPROVED** [review]
LGTM

@ebeahan Do you know if we have any CI checks that could prevent this from happening as this is not a valid type in the first place?

**Comment by eyalkoren** [comment]
> @ebeahan Do you know if we have any CI checks that could prevent this from happening as this is not a valid type in the first place?

@ruflin Elasticsearch's CI will now [tell us](https://github.com/elastic/elasticsearch/pull/97901/files#diff-5de719b6a576263ffb32a9a7a1754078f91b12abf0d4fe7141faeb7a91e6b66dR289) if such slips in 😉

**Review by ebeahan — APPROVED** [review]
LGTM. Can we also reference this fix in the [CHANGELOG.next entry](https://github.com/elastic/ecs/blob/main/CHANGELOG.next.md?plain=1#L18)?

**Comment by ebeahan** [comment]
> Do you know if we have any CI checks that could prevent this from happening as this is not a valid type in the first place?

AFAIK, surprisingly not. Filed an issue: https://github.com/elastic/ecs/issues/2249

**Review by kgeller — APPROVED** [review]

**Comment by eyalkoren** [comment]
Anything blocking this from being merged?

**Comment by kgeller** [comment]
> Anything blocking this from being merged?

@eyalkoren I assumed it was waiting on an outstanding review from @norrietaylor , but will merge if you all are ready

**Pull request merged**
