### PR TITLE
added http.forwarded_for #874

### PR DESCRIPTION
**Pull request by dainok**
Added http.forwarded_for for HTTP X-Forwarded-For header. See https://github.com/elastic/ecs/issues/874

### CODE REVIEW

**Comment by andrewstucki** [comment]
Not that I see a need to necessarily introduce them, but wonder why the singling out of `X-Forwarded-For`? If we wanted to introduce defacto standard proxy header support shouldn't we add `X-Forwarded-Host` and `X-Forwarded-Proto` at the same time?

**Comment by dainok** [comment]
@andrewstucki you're right, here the additional fields.

**Comment by webmat** [comment]
Thanks for submitting this, @dainok! I agree we need to address the need for these HTTP headers in ECS.

I think we should focus on adding support for all HTTP headers, rather than the X-Forwarded family however. This has been discussed here https://github.com/elastic/ecs/pull/554 in the past but the discussion petered out at the time.

We'll see if we can get some attention to that.

**Comment by dainok** [comment]
@webmat Ok, let me know if I can do more. Close the PR if you wish.

**Pull request closed without merging**
