### PR TITLE
RFC Stage 1: Device fields

### PR DESCRIPTION
**Pull request by AlexanderWert**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)?
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)?
- If submitting code/script changes, have you verified all tests pass locally using `make test`?
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes?
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- Have you added an entry to the [CHANGELOG.next.md](https://github.com/elastic/ecs/blob/main/CHANGELOG.next.md)?

### CODE REVIEW

**Review by kgeller — APPROVED** [review]
LGTM!

**Comment by kgeller** [comment]
@AlexanderWert these look great. Could you also update the stage in the RFC readme?

**Comment by AlexanderWert** [comment]
@kgeller Thanks! I updated the readme as well now.

**Comment by kgeller** [comment]
@AlexanderWert Thanks! Merge whenever you're ready

**Pull request merged**
