### PR TITLE
Remove `ignore_above` parameter when indexing is disabled on field

### LINKED ISSUE #1481: Remove `ignore_above` setting when not indexing field
Certain ECS fields are type `keyword` but are also not:

* searchable (`index: false`)
* used in aggregations, sorting, or scripting (`doc_values: false`)

The ECS tooling's behavior is to set `ignore_above: 1024` for all `keyword` fields.

However, `ignore_above` should not be present when `index: false` and `doc_values: false` are set on a field.

### PR DESCRIPTION
**Pull request by ebeahan**
Remove the default `ignore_above: 1024` parameter applied to all `keyword` type fields when `index: false` is set on the field.

Closes #1481

### CODE REVIEW

**Review by djptek — APPROVED** [review]
LGTM

**Comment by ebeahan** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by ebeahan** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by ebeahan** [comment]
Merging without the ✅ from `elasticsearch-ci/docs` (CI challenges), but this change doesn't impact the docs at all.

**Pull request merged**
