### PR TITLE
Threat intelligence RFCs stage 2 addenda

### PR DESCRIPTION
**Pull request by ebeahan**
Incorporate changes from the threat intelligence addenda for stage 2: #1502 

[Docs preview](https://ecs_1504.docs-preview.app.elstc.co/diff)

### CODE REVIEW

**Review by rylnd — COMMENTED** [review]
Gave this a once-over:

* Verified docs preview looks correct
* Verified that the JSON and YML files correctly declare enrichments as nested, and contain all relevant fields

The only thing potentially missing is an update to the original RFCs themselves? I know the changelog accounts for this, but I'm not sure if we should also include a mention of these changes in RFCs 8 and 21.

**Comment by ebeahan** [comment]
@rylnd #1502 added the changes to each of the two RFC proposals and example field definitions. Or is there something else we should capture?

I did link #1502 at the bottom of both RFCs before merging:

* https://github.com/elastic/ecs/blob/master/rfcs/text/0008-threat-intel.md#rfc-pull-requests
* https://github.com/elastic/ecs/blob/master/rfcs/text/0021-threat-enrichment.md#rfc-pull-requests

**Comment by rylnd** [comment]
> I did link #1502 at the bottom of both RFCs before merging:

Ah, yep! https://github.com/elastic/ecs/pull/1502/commits/25eb02c4b3ac625abf9fbd8e6ffdb5535a4a742a is what I was asking about. LGTM!

**Review by rylnd — APPROVED** [review]
See previous comments; approved!

**Review by djptek — APPROVED** [review]
Structure and Language Good, saw a docs word omission while I was in there, opened https://github.com/elastic/ecs/pull/1505 to avoid noise here. Deferring to SME for Content

**Pull request merged**
