### PR TITLE
Remove schema.json and the code that generates it

### PR DESCRIPTION
**Pull request by webmat**
This file is no longer used to power the SIEM field browser.

### CODE REVIEW

**Comment by webmat** [comment]
Its creator didn't even end up using it 🤷‍♂

**Comment by ruflin** [comment]
🤦‍♂ That doesn't mean someone else is using it. I'm good with this "breaking change" but lets at least have it in the changelog so users know.

**Comment by webmat** [comment]
Yeah, someone else may be using it.

If anyone needs this, please make yourselves heard, even if this PR has been merged already :-)

**Comment by webmat** [comment]
Will move this changelog entry to "tooling" after https://github.com/elastic/ecs/pull/633

**Comment by pete-otaqui-sky** [comment]
Hi - I'd like to ask for this to be put back in.  We'd like to be able to validate ECS compatibility using AWS API Gateway, which depends on JSON Schema.  Would you like a PR for putting it back?

**Comment by ebeahan** [comment]
Hi @pete-otaqui-sky. Currently ECS doesn't maintain a JSON format of the schema as part of the [generated artifacts](https://github.com/elastic/ecs/blob/master/generated/). However, the [ecs_nested.yml](https://github.com/elastic/ecs/blob/master/generated/ecs/ecs_nested.yml) file is intended to be consumed programmatically and YAML can be painlessly converted to a JSON format if required for your needs.

Please feel free to open a new issue if you'd like to discuss further or have additional questions.

**Pull request merged**
