### PR TITLE
Create login.yml

### PR DESCRIPTION
**Pull request by mr1716**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? yes
- If submitting code/script changes, have you verified all tests pass locally using `make test`? yes
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? yes
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- Have you added an entry to the [CHANGELOG.next.md](https://github.com/elastic/ecs/blob/main/CHANGELOG.next.md)?

### CODE REVIEW

**Comment by djptek** [comment]
Hi @mr1716 please could you follow the [RFC Process](https://github.com/elastic/ecs/blob/main/rfcs/README.md) to propose new Field Sets for ECS

Thanks for your input

**Comment by mr1716** [comment]
@djptek How would I follow steps 3 and beyond? I thought this did a good job for steps 1 and 2?

**Comment by djptek** [comment]
Hi @mr1716 the recommendation is to follow the step outlined in [ECS RFCs How this works](https://github.com/elastic/ecs/blob/main/rfcs/README.md#how-this-works)

It may seem like a lot of process, however, in our experience, it's really worth doing the detail on all the steps to improve the prospect of your RFC being added to ECS for the benefit of the whole community.

`login` looks interesting as a candidate field, however, if you don't think the RFC process is right for your need, there is also an ECS toolset to allow you to add [custom fields](https://github.com/elastic/ecs/blob/main/docs/using-ecs/custom-fields.asciidoc) locally to your own implementation

**Comment by mr1716** [comment]
@djptek If this were something that was useful for custom fields for my own toolset, I would not be going through the RFC process. The Azure is just 1 example where login information is useful. If I were to use ECS to find MFA information used for logins by users, which fields would one use??

**Comment by djptek** [comment]
Hi @mr1716 

>> if I were to use ECS to find MFA information used for logins by users, which fields would one use??

Please can you ask this question in [ECS Discuss Forum](https://discuss.elastic.co/tags/c/observability/82/ecs-elastic-common-schema)  which is a more appropriate place than GitHub, thanks!

**Pull request closed without merging**
