### PR TITLE
[RFC] Multiple Users - Update to align with new proposal stages

### PR DESCRIPTION
**Pull request by ebeahan**
Update the multiple users RFC proposal's stage to align with new RFC [proposal stages](https://elastic.github.io/ecs/stages.html).

### CODE REVIEW

**Comment by epixa** [comment]
For multi-user, what items remain before we can consider stage 3?

**Comment by ebeahan** [comment]
The stage 3 criteria (minus the PR step):

- [x] Included multiple real-world example source documents
- [x] Existing or newly raised questions and concerns are addressed
- [ ] No objections from the sponsor, ECS team, or subject matter experts

I feel the proposal doc itself is complete, with several examples and all captured concerns having a documented resolution. The only outstanding item I see is an agreement that the fields as defined are complete. I don't expect any objections to arise, though.

Implementation of ECS 1.8 is ongoing (e.g., https://github.com/elastic/beats/issues/23118) without any major hurdles AFAIK. The multiple user changes are being released as `beta` in 1.8, giving us some flexibility if any adjustments become needed.

**Comment by ebeahan** [comment]
After more discussion out-of-band, the ECS team feels comfortable and confident considering the multiple users RFC as finished.

@adriansr @marc-gr, you both have been doing most of the ECS 1.8 implementation work in beats/integrations (https://github.com/elastic/beats/issues/23118) to adopt the multiple users' fields. Any issues or feedback you have from that work that should be captured before considering the multiple users RFC finished?

**Comment by adriansr** [comment]
@ebeahan I can't think of any issue that could prevent the RFC to be finished.

Only issue that I remember is not being able to map some events that modify multiple users at the same time, understandable as related can't be an array.

And at some point we should give some thought to similar changes for `group.*` fields.

**Comment by ebeahan** [comment]
From the feedback, sounds like we're all in agreement to consider this RFC finished. 🎉 

I've updated the proposal to reflect that change. Once this is merged, I'll open a separate PR to remove the `beta` attribute from these fields in the schema.

**Comment by ebeahan** [comment]
@epixa Would you give this one final look?

**Review by epixa — APPROVED** [review]
LGTM

**Pull request merged**
