### PR TITLE
Fix exmple type to example for fields.yml and process.yml

### PR DESCRIPTION
**Pull request by codebrain**
Fix typo, should read as `example`

### CODE REVIEW

**Comment by codebrain** [comment]
@ruflin - its proving to be a little difficult to run this in Windows :)

**Comment by codebrain** [comment]
Looks like I might be able to workaround this by editing the generated files directly?

**Comment by ruflin** [comment]
@codebrain Sorry about that Windows issue.We should probably fix that. If you give me permission on your branch, I can run it for you.

**Comment by webmat** [comment]
@codebrain I'd love your help on making this more easy to run on Windows at some point. What are the failures you're seeing?

Oh, is it just because of `make`? I see Beats partially solves this with mage...

Any suggestions welcome on replacing make :-) Could be mage, could be another task runner in Python.

**Comment by webmat** [comment]
I just noticed this is a PR to the 1.0 branch. I'll reapply your contributions on top of master, and then backport to 1.0.

Need to keep the workflow uniform :-)

**Pull request closed without merging**
