### PR TITLE
GitHub link 1.10

### PR DESCRIPTION
**Pull request by djptek**
Have you signed the contributor license agreement? Y
Have you followed the contributor guidelines? Y
For proposing substantial changes or additions to the schema, have you reviewed the RFC process? n/a
If submitting code/script changes, have you verified all tests pass locally using make test? Y
If submitting schema/fields updates, have you generated new artifacts by running make and committed those changes? Y
Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Y
Have you added an entry to the CHANGELOG.next.md? Y

Simulate backport of `Fix ecs GitHub repo link source branch` #1393 vs 1.10

### CODE REVIEW

**Review by kgeller — APPROVED** [review]
lgtm

**Comment by ebeahan** [comment]
I think we could just backport #1393 once merged, right?

Or is this PR for testing?

**Comment by djptek** [comment]
@ebeahan the PR was initially for testing, though I'll run a diff on this branch vs 1.x for sanity's sake as this one has been thorny & I'd like to be triple sure

**Comment by djptek** [comment]
@ebeahan @kgeller do we want a backport of #1393 to 1.10? if so, I'll do that via the tool & in either case I'm closing this PR

**Comment by kgeller** [comment]
@djptek I'd wait for @ebeahan 's opinion, but I say since it's not impacting the schema, I don't see any hair in putting it into 1.10

**Pull request closed without merging**
