### PR TITLE
[RFC] Threat Enrichment - Stage 2

### PR DESCRIPTION
**Pull request by rylnd**
As follow up to #1400, this is the stage 2 RFC for threat enrichment. I believe that most of the stage 2 work has already been done, but I'm happy to be told otherwise.

[RFC Preview](https://github.com/rylnd/ecs/blob/threat-enrichment-stage-2/rfcs/text/0021-threat-enrichment.md)

### TODO 
- [ ] If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes?
- [ ] Have you added an entry to the [CHANGELOG.next.md](https://github.com/elastic/ecs/blob/master/CHANGELOG.next.md)?

### CODE REVIEW

**Comment by rylnd** [comment]
@ebeahan my first question for stage 2 is:  should this PR promote the declared fields so that they are included as beta fields, or is that done once this is merged (a la https://github.com/elastic/ecs/pull/1438) ?

**Comment by ebeahan** [comment]
@rylnd We've found separating the RFC PR from the implementation PR is cleaner, and it lets us focus more on the content and details of the proposal vs. clogging up the RFC discussion with potential ECS build issues, testing, tooling challenges, etc.

**Review by devonakerr — APPROVED** [review]
Minor updates reflecting the stage advancement of this RFC look good to me.

**Review by ebeahan — APPROVED** [review]
LGTM 👍 

### Review Criteria for Stage 2

- [x] Opened pull request for this draft revising the existing proposal
- [x] Completed field definitions
- [x] Included a real world example source document
- [x] Identifies scope of impact of changes to ingestion mechanisms (e.g. beats/logstash), usage mechanisms (e.g. Kibana applications, detections), and the ECS project (e.g. docs, tooling)
- [x] Subject matter experts weighed in on technical utility of field definitions in the pull request

**Pull request merged**
