### PR TITLE
added time_to_expiry field that indicates the number of milliseconds …

### PR DESCRIPTION
**Pull request by osherdp**
…until the server's certificate will get expired

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)?
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)?
- If submitting code/script changes, have you verified all tests pass locally using `make test`?
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes?
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- Have you added an entry to the [CHANGELOG.next.md](https://github.com/elastic/ecs/blob/master/CHANGELOG.next.md)?

### CODE REVIEW

**Comment by ebeahan** [comment]
Hi @osherdp - is your needed use case(s) something that can be accomplished with a range query and the existing `tls.server.x509.not_after`/`tls.server.x509.not_before` fields?

Example using Lucene query syntax:

```
tls.server.x509.not_after:[now TO now+30d]
```

Or using query DSL:

```json
{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "tls.server.x509.not_after": {
              "lte": "now+30d",
              "gte": "now"
            }
          }
        }
      ]
    }
  }
}
```

**Comment by osherdp** [comment]
@ebeahan you can read discussion in the referenced issue
Plugins like elastalert and regular users need a solution based on the query language

**Comment by ebeahan** [comment]
Yes I did review the referenced issue. After reviewing that discussion, it seemed like the primary motivation for adding the `x509.time_to_expiry` was to perform a search for which certifications would be expiring in the near future? 

You can use a range query such as `tls.server.x509.not_after:[now TO now+30d]` to achieve what I believe is the desired search results in Kibana in the Discover app:

Screen Shot 2020-10-22 at 11 51 51 AM

We can, of course, continue discussing the addition of a new field, but I first wanted to clear up any possible confusion around the currently available capabilities.

**Comment by osherdp** [comment]
@ebeahan alright, thanks
I was not aware of this option

**Pull request closed without merging**
