### PR TITLE
Add host.containerized and os.codename

### PR DESCRIPTION
**Pull request by andrewvc**
This came up in https://github.com/elastic/ecs/issues/75 and https://github.com/elastic/beats/issues/9154.

These fields seem useful. I notice no other fields in ECS are boolean, so this may be a first.

### CODE REVIEW

**Comment by webmat** [comment]
Thanks @andrewvc!

Not exactly the same semantics, but check out the definition for the new field `os.full`, wrt OS code names: https://github.com/elastic/ecs#os. Would this work for your use case?

As for `host.containerized`, a few things:

- I applaud you on your courage to introduce the first `boolean`! However you can only get that distinction if you actually make the field `boolean`, right now it's `keyword` ;-)
- Out of curiosity, in this case you're using `host` to report information from the point of view of the containerized process, correct? Can you expand on the situation, and perhaps give an example event how you would envision this?
  - I wonder if the `.containerized` field shouldn't be elsewhere, like perhaps `process.containerized` or `service.containerized`.

**Comment by webmat** [comment]
Oh that could work too, indeed. You're right that the current `host.type` example sounds redundant vs `cloud.machine.type`.

**Comment by andrewvc** [comment]
Is there still interest in this issue? CC @ppf2

**Comment by webmat** [comment]
We'll need to step back and have a broader discussion, for what happens here.

I could see some value in adding `os.codename`, although `os` already has a pretty good amount of fields. Not sure if adding `codename` in adition to `name` and `full` is all that useful.

As for `host.containerized`, we've discussed in other places that `host` was purely meant for a VM or a physical host. Not for a container. The container details belong in `container`. Do you know how `host.containerized` is being populated in Beats? I'd like to better understand the semantics.

The fix for what @ppf2 reported is actually a bugfix in Beats. If Beats populates these custom fields (at least custom for now), there should be a field definition added in `libbeat/_meta/fields.common.yml`.

**Comment by andrewvc** [comment]
@webmat I'm +1 for fixing this in beats as custom fields. I'm going to close this issue given that.

**Comment by ruflin** [comment]
@webmat We should sync up offline around if host is also mean for containers and others. Not sure if we are on the same page here.

**Pull request closed without merging**
