### PR TITLE
Add http.request.method and http.version

### PR DESCRIPTION
**Pull request by willemdh**
Should fix https://github.com/elastic/ecs/issues/41 Please review

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for the PR. Could you sign the CLA (https://www.elastic.co/contributor-agreement) and add a CHANGELOG entry?

**Comment by willemdh** [comment]
Updated changelog and signed the CLA

**Comment by karmi** [comment]
Hi @willemdh, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/ecs/pull/45.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by willemdh** [comment]
@karmi Added my work email, is it ok now?

**Comment by karmi** [comment]
Hi @willemdh, yes, thanks! The check is green now.

**Comment by ruflin** [comment]
@willemdh Thanks for the contribution.

**Pull request merged**
