### PR TITLE
Progressing service.environment RFC to stage 2

### PR DESCRIPTION
**Pull request by eyalkoren**
[Preview of the proposal doc](https://github.com/elastic/ecs/blob/service-environment-rfc-stage2/rfcs/text/0002-rfc-environment.md)

### CODE REVIEW

**Comment by ebeahan** [comment]
Stage 2 Criteria

- [ ] Opened pull request for this draft revising the existing proposal
- [ ] Completed field definitions
- [ ] Included a real-world example source document
- [ ] Identifies scope of impact of changes to ingestion mechanisms (e.g. beats/logstash), usage mechanisms (e.g. Kibana applications, detections), and the ECS project (e.g. docs, tooling)
- [ ] Subject matter experts weighed in on the technical utility of field definitions in the pull request

**Comment by ebeahan** [comment]
Thanks for moving this forward, @eyalkoren. Like we chatted about elsewhere, this proposal is in great shape for stage 2 already.

@cyrille-leclerc @exekias @sqren all helped contribute to the earlier stages of this doc. I would appreciate it if you'd share any feedback or concerns about moving this forward.

@exekias, are you still ok with being listed as the sponsor?

**Comment by cyrille-leclerc** [comment]
I have no concern regarding `service.environment` being the ECS field to describe the environment on which an application is being deployed

**Comment by exekias** [comment]
> @exekias, are you still ok with being listed as the sponsor?

SGTM!

**Review by ebeahan — APPROVED** [review]

**Comment by ebeahan** [comment]
Stage 2 implementation PR: https://github.com/elastic/ecs/pull/1541

**Pull request merged**
