### PR TITLE
Define fields to allow representing multiple users in an event.

### LINKED ISSUE #809: [ECS] Multiple users in an event proposal
After reviewing proposals and discussions, new and old, private and public (#117, #234, #589, #678, elastic/beats#9963, elastic/beats#10111, elastic/beats#10192), here's a high level proposal. I'd like to get feedback on this.

When `user.*` is populated at the root of an event, it's meant to capture the user performing an action, or the only user relevant to an event, when that's the situation.

The goal of this proposal is to solve the following use cases:

1. User A creates or deletes User B (no prior or post state)
2. User A modifies User B (there's a prior and a post state)
3. User A assumes the identity of User B (or fails to)

One thing to note, is that with real-time privilege escalation (e.g. sudo, MacOS modal) or auditing frameworks like auditd, it's useful to be able to identify all 3 of these additional users concurrently, in a single event.

Here are locations I propose we could nest the user schema, to represent various use cases:

* user.effective.*
* user.target.*
* user.new.*

Note that in each of these cases, we are nesting the `user` schema as a new name, similar to what we do with `process.parent`. To give a concrete example the effective user name would be at `user.effective.name` (not at `user.effective.user.name`).

### user.effective.*
 
Used to identify the final identity, when logging in remotely as another user, or escalating privileges.

Simplified privilege escalation example, where "alice" escalates privileges to "root":

```JSON
{
  "user": {
    "name": "alice",
    "effective": {
      "name": "root"
    }
  }
}
```

### user.target.*

Used to identify the user being modified, or targeted by an action.

Simplified user management example, where "root" modifies user "bob":
```JSON
{
  "user": {
    "name": "root",
    "target": {
      "name": "bob"
    }
  }
}
```

### user.new.*

Used to identify what was changed about the user. Ideally this would only capture the difference, not repeat all values.

Simplified user management example, when an existing user is modified, for example changing user name. Here user "bob" is renamed "foo" by "root":
```JSON
{
  "user": {
    "name": "root",
    "target": {
      "name": "bob"
    },
    "new": {
      "name": "foo"
    }
  }
}

```

Note: The creation of a new user would only use `user.target`, not `user.new`. `user.new` should only be used.

### Putting it all together

If it's possible to determine who was the original user prior to privilege escalation, a full event could look like this:

```JSON
{
  "user": {
    "name": "alice",
    "effective": {
      "name": "root"
    },
    "target": {
      "name": "bob"
    }
  }
}
```

The action being observed should be captured in `event.action`.

If the event is user management, the category fields should be `event.category: [ "iam" ]` and `event.type: [ "user" ]`  with a secondary entry in `event.type`, whichever is more appropriate: "creation", "deletion" or "change".

If the event is authentication and privilege escalation, `event.category: [ "authentication" ]`,  `event.type: ["start"]` and `event.outcome` either "success" or "failure".

## Discussion points

Nowhere in the above plan do we use the current nestings of the `user` field set: `client.user`, `destination.user`, `host.user`, `server.user`, `source.user`.

I'm wondering if people are using `host.user` or if we should deprecate it for removal in ECS 2.0.

I'd also like to know if the 4 nestings under the network-related field sets are currently being used. I realize that folks may have used for example `source.user` and `destination.user` to model remote logons or the "acting" vs "target" users, with ECS specifying nothing yet on how these interactions should be modelled until now. I'd like to get your input if the plan above makes sense.

Are there other uses that are actually network-related for `source.user` and `destination.user`?

### PR DESCRIPTION
**Pull request by webmat**
This PR implements the proposal discussed in #809. In short, we now reuse all `user` fields in 3 new places, in order to allow capturing more relevant users on a given event:

* `user.effective.*` is used to capture the effective user in cases of privilege escalation.
* `user.target.*` is used to capture a distinct user that is affected by an action, like IAM: Alice creates/suspends/deletes Bob.
* `user.changes.*` is used to capture the changes to an existing user. It's worth pointing out that only the attributes that change for the user are expected to be populated here.

For now this PR simply adds the fields. We don't yet have a good way to have either contextual definitions around field reuse, nor a place to document this via free form text, in the user page. This will come as a later addition.

I'm opening this PR in a straighforward manner, by directly introducing these fields. However I'm thinking this major addition is probably a good candidate to move through the RFC process.

What do you think @epixa @ebeahan @tsg?

Closes #809

### CODE REVIEW

**Comment by webmat** [comment]
Ping all of the fine folks who chimed in on #809: @leehinman @neu5ron @janniten @willemdh @rw-access :-)

**Comment by ebeahan** [comment]
+1 for moving this additions through the RFC process 😃

**Comment by l0x-c0d3z** [comment]
I like the approach. I've been having issues mapping IAM audit logs recently. It also sets a good precedent for stuff like 'process.target.*' (for stuff like cross-process access and code injections).

**Comment by webmat** [comment]
Closing in favor of #1066 (see also RFC 0007 stage 3 PR #1017)

**Pull request closed without merging**
