### PR TITLE
Remove `yamllint` dependency

### PR DESCRIPTION
**Pull request by ebeahan**
The `yamllint` dependency is only used for `make yamllint`, and `make yammlint` is not enforced in any build step (e.g., `make check`). Also, I suspect most folks rely on text editors for equivalent functionality, and it's unnecessary to include it as a dep.

Also adding comments noting the associated licenses for each existing dependency in the Pipfile.

### CODE REVIEW

**Review by djptek — COMMENTED** [review]
I ran `make yamllint` and am not convinced that contributors are submitting well-formatted YAML, which is a concern.

I opened an issue with options on how we might address that https://github.com/elastic/ecs/issues/1662 

I also submitted a PR with fixes to the Yaml, and an alternative configuration for Yamllint
https://github.com/elastic/ecs/pull/1661

**Comment by djptek** [comment]
Thanks @ebeahan for walking me through the rationale, this is a great idea, LGTM!

**Review by djptek — APPROVED** [review]
LGTM!

**Comment by ebeahan** [comment]
Going to propose a different direction in a new PR.

**Pull request closed without merging**
