### PR TITLE
[Docs] Fix GitHub repo link using source_branch + templates

### PR DESCRIPTION
**Pull request by djptek**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Y
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)? Y
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? n/a
- If submitting code/script changes, have you verified all tests pass locally using `make test`? Y
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? Y
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Y
- Have you added an entry to the [CHANGELOG.next.md](https://github.com/elastic/ecs/blob/master/CHANGELOG.next.md)? Y

Replaces https://github.com/elastic/ecs/pull/1338

### CODE REVIEW

**Comment by djptek** [comment]
memo: add credit to @ebeahan in commit - thanks for help

**Review by kgeller — APPROVED** [review]
LGTM!

Just one question, will the `:ecs_generated_version:` in the `index.asciidoc` be an additional version location we'll be updating with release/FF?

**Comment by ebeahan** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by ebeahan — APPROVED** [review]
Nice work, @djptek!

Optional, but now that the `ecs_generated_version` attribute exists, we could also update the other remaining reference to `ecs_version`:

https://github.com/elastic/ecs/blob/master/scripts/templates/fields.j2#L5

**Comment by djptek** [comment]
applied suggestion https://github.com/elastic/ecs/pull/1381#pullrequestreview-651424030 and merging

**Pull request merged**
