### PR TITLE
Add URL and domain threat.{fields}

### LINKED ISSUE #2081: threat.(enrichments.)indicator.domain missing
**Description of the issue:**
`threat.indicator.domain` and `threat.enrichments.indicator.domain` are missing from the [fieldset](https://github.com/elastic/ecs/blob/main/schemas/threat.yml), but are present in the example [usage](https://www.elastic.co/guide/en/ecs/current/ecs-threat-usage.html) documentation.

**Usage**
```
{
    "@timestamp": "2019-08-10T11:09:23.000Z",
    "event": {
        "kind": "enrichment", 
        "category": "threat", 
        "type": "indicator", 
        "severity": 7,
        "risk_score": 10.0,
    },
    "threat: {
        "indicator": { 
            "first_seen": "2020-11-05T17:25:47.000Z",
            "last_seen": "2020-11-05T17:25:47.000Z",
            "modified_at": "2020-11-05T17:25:47.000Z",
            "sightings": 10,
            "type": [
                "ipv4-addr",
                "port",
                "domain-name",
                "email-addr"
            ],
            "description": "Email address, domain, port, and IP address observed during an Angler EK campaign.",
            "provider": "Abuse.ch",
            "reference": "https://urlhaus.abuse.ch/url/abcdefg/",
            "confidence": "High",
            "ip": 1.2.3.4,
            "domain": "malicious.evil",
            "port": 443,
            "email.address": "phish@malicious.evil",
            "marking: {
                "tlp": "WHITE"
            },
            "scanner_stats": 4
        }
    },
    "related": { 
        "hosts": [
            "malicious.evil"
        ],
        "ip": [
            1.2.3.4
        ]
    }
}
```

### PR DESCRIPTION
**Pull request by peasead**
Added URL and domain indicators and enrichments

Closes #2081 

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? Yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? NA
- If submitting code/script changes, have you verified all tests pass locally using `make test`? Yes
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? Yes
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. Yes
- Have you added an entry to the [CHANGELOG.next.md](https://github.com/elastic/ecs/blob/main/CHANGELOG.next.md)? No

### CODE REVIEW

**Review by taylor-swanson — COMMENTED** [review]
Looks like we are missing a changelog entry. Otherwise the changes seem good to me. @kgeller, anything else missing or does this look good to you?

**Comment by peasead** [comment]
@taylor-swanson do you need me to add the changelog?

**Comment by taylor-swanson** [comment]
Yeah just a brief entry under the Added section in Schema Changes in `CHANGELOG.next.md` should do.

```diff
## Unreleased

### Schema Changes

#### Breaking changes

#### Bugfixes

* remove duplicated `client.domain` definition #212

#### Added

* Added URL and domain indicators and enrichments #2117
```

Looks like the branch needs to be updated as well, so you could do both at the same time (just need to merge changes from main)

**Comment by kgeller** [comment]
@peasead @taylor-swanson I just commented on the issue, but I think that this PR is unnecessary due to existing URL nestings. I think all we need is an update to the usage docs.

**Comment by peasead** [comment]
Thanks @kgeller 

I see the nested `threat.indicator.url.*` under [Field Reuse](https://www.elastic.co/guide/en/ecs/current/ecs-threat.html#_field_reuse_25). Where do I update the usage docs? I feel like they're generated, not manually created?

**Comment by kgeller** [comment]
@peasead you'll update here https://github.com/elastic/ecs/blob/main/docs/fields/usage/threat.asciidoc

**Comment by peasead** [comment]
Thanks @kgeller I'll do that.

**Pull request closed without merging**
