### PR TITLE
Added Confidence Rating to ECS

### PR DESCRIPTION
**Pull request by secops4thewin**
Added the following line to threat ECS

 * threat.confidence
    _The confidence rating of the threat, ranging from 0 - 100, following STIX 2.0 confidence rating_

### CODE REVIEW

**Comment by secops4thewin** [comment]
I have now signed the contributor agreement :)

**Comment by ebeahan** [comment]
Hi @secops4thewin 👋 

If you want to propose adding the `threat.confidence` field, feel free to join into the discussions in-progress over in #1127 concerning the `threat.*` RFC.

**Comment by ebeahan** [comment]
@shimonmodi @dcode @peasead - this is a proposed field addition to the `threat.*`. Let's continue the discussion in #1127, but I wanted to call attention to the suggestion before closing.

**Comment by peasead** [comment]
https://github.com/elastic/ecs/pull/1127#issuecomment-758247401

**Pull request closed without merging**
