### PR TITLE
[1.10] Fix ecs GitHub repo link source branch (#1393)

### PR DESCRIPTION
**Pull request by djptek**
Backports the following commits to 1.10:
 - Fix ecs GitHub repo link source branch (#1393)

### CODE REVIEW

**Comment by djptek** [comment]
The build shows no changes for the docs diff - that's desired behavior as the code I removed was vestigial from a previous PR and shouldn't have impacted the docs

**Comment by djptek** [comment]
waiting on https://github.com/elastic/ecs/pull/1399

**Review by ebeahan — APPROVED** [review]
Docs preview LGTM: https://ecs_1398.docs-preview.app.elstc.co/guide/en/ecs/1.10/ecs-artifacts.html

Anything else we're waiting on here?

**Comment by djptek** [comment]
#1399 is closed, sorry for wasting time on that. Thanks for review, Merging

**Comment by djptek** [comment]
actually no, on reflection, this has the "docs" folder regression. Closing this PR, I'll do a fresh backport

**Pull request closed without merging**
