### PR TITLE
Move to --direct_html doc build option:

### PR DESCRIPTION
**Pull request by webmat**
- Better asciidoctor compatibility
- Moar fast builds

Relates to https://github.com/elastic/docs/pull/1559

### CODE REVIEW

**Comment by nik9000** [comment]
I don't think you need to do this now that I've merged https://github.com/elastic/docs/pull/1659

**Comment by nik9000** [comment]
With that PR adding the option will just log a happy message. Nice and all, but not needed.

**Comment by webmat** [comment]
I always build the docs locally though, when working on docs. So that helps speed there too, no?

**Comment by nik9000** [comment]
> I always build the docs locally though, when working on docs. So that helps speed there too, no?

Nah. Once you pull the most recent version of the docs that flag doesn't do anything. It was important for every other repo to add it because it wasn't the default. But because you were last I switched it to the default as soon as I merged you.

**Comment by webmat** [comment]
Ah, thanks for the clarification!

**Pull request closed without merging**
