### PR TITLE
Change `url.port` to long type

### PR DESCRIPTION
**Pull request by praseodym**
This is consistent with other `port` field types.

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @praseodym, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/ecs/pull/274.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by webmat** [comment]
@praseodym Could you list this change in the Unreleased section under "Improvements", please? Check out the format of the other entries and keep it simple :-)

**Comment by ruflin** [comment]
We should list this at least in the changelog as Improvement? In the end it does not make really difference if it is int or long.

**Comment by webmat** [comment]
It's a more "lax" requirement, so it satisfies the previous definition indeed. So an improvement, not a breaking change.

**Comment by praseodym** [comment]
Done!

**Comment by ruflin** [comment]
This needs a rebased on master.

**Comment by webmat** [comment]
@praseodym Sorry for messing up here, and thanks for your contribution.

We're working on improving the process for this new repo, so these mistakes don't happen again. 

For simplicity's sake we merged #339 instead.

**Pull request closed without merging**
