### PR TITLE
Adding `risk.*` as beta

### PR DESCRIPTION
**Pull request by kgeller**

### CODE REVIEW

**Comment by ajosh0504** [comment]
@kgeller In that case, this LGTM!

**Comment by MikePaquette** [comment]
Thanks @kgeller for creating this Pull request.

Could we enhance the description a bit to help users avoid confusion with the `event.risk_score` and `event.risk_score_norm` fields?
Maybe by updating the title, short, and description as follows:

1. `title: Risk information`
2. `short: Fields for describing risk score and level.`
3. `description: > Fields for describing risk score and risk level of entities such as hosts and users.  These fields are not allowed to be nested under event.*.  Please continue to use event.risk_score and event.risk_score_norm for event risk.`

**Comment by kgeller** [comment]
@MikePaquette updated!

**Comment by ajosh0504** [comment]
@kgeller I will also clarify this in the Stage 3 PR as per your request.

**Review by MikePaquette — APPROVED** [review]
LGTM,  thanks!

**Pull request merged**
