### PR TITLE
Adding field vendor.name to Package ECS mapping

### PR DESCRIPTION
**Pull request by lkuik**
Pull request to add vendor name as an ECS field for the package ECS mappings to accompany the already existing fields such as package version and package name

### CODE REVIEW

**Comment by lkuik** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [17b742b](https://github.com/elastic/ecs/commit/17b742b0356235448fa1c7faab5078d291733587)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

I have already signed earlier this morning

**Comment by lkuik** [comment]
This PR links to feature request submitted here:
https://github.com/elastic/ecs/issues/2203

**Comment by kgeller** [comment]
> I have already signed earlier this morning

It appears that you signed the CLA with a different email address (internet provider email) than was associated with the commit (company email).

**Comment by lkuik** [comment]
My apologies @kgeller , not sure why it ended up committing with the wrong userid.
Is best path forward to just close this out cancel the PR, and resubmit and ensure the commit is with my personal github?

**Comment by lkuik** [comment]
Closing this PR out as was submitted with wrong GitHub ID, will re-submit to match ID on file for CLA

**Comment by kgeller** [comment]
@lkuik no problem! I see it's already complete, but yes the best path is to have that cla signed with whatever is associated with the commit.

**Comment by lkuik** [comment]
Yup resubmitted and it looks good now! Thanks
On May 1, 2023 10:45 a.m., Kylie Meli wrote:


@lkuik no problem! I see it's already complete, but yes the best path is to have that cla signed with whatever is associated with the commit.

**Pull request closed without merging**
