### PR TITLE
Standardize additional cloud metadata

### PR DESCRIPTION
**Pull request by graphaelli**
Adds:

* account.name
* project.id
* project.name

### CODE REVIEW

**Comment by graphaelli** [comment]
This does not impact Infra UIs - `project.id` is already supplied by the `add_cloud_metadata` processor in beats, `account.id` is supplied the metricbeat aws module, `project.name` is new.

**Comment by urso** [comment]
+1 on adding project/account information to the cloud namespace.

@kvch @kaiyan-sheng @narph You've been working with Cloud (AWS, Azure, GCP) to some extend. Any other meta-data in mind we would like to add?

**Comment by webmat** [comment]
Thanks @urso. What I'm looking for here is actually any concerns from getting this data from people that know about the implementation of the meta data collector in Beats.

Although if additional fields could be useful, additional PRs are always welcome :-)

**Comment by kvch** [comment]
@webmat It would be great to have appropriate field names for such services. For example, I use `resource.*` fields to identify and describe the states of the AWS/GCP resources from the event. But I understand, it is outside of the scope of this PR.

**Comment by webmat** [comment]
@urso @kvch Thanks for the feedback. So there's no issues in getting this information from the metadata collector?

**Comment by urso** [comment]
I don't think so.

**Comment by webmat** [comment]
Oh wait, getting carried away. Did you want to wait on @simitt's review before I merge, Gil?

**Comment by graphaelli** [comment]
@webmat Changelog pushed, @simitt is on board

**Pull request merged**
