### PR TITLE
[event] Cleanup Event Fields

### PR DESCRIPTION
**Pull request by nicpenning**
Added "is" to clear up a sentence and made more fields stick out using the ` characters which makes it more consistent with the rest of the documentation.

### CODE REVIEW

**Comment by nicpenning** [comment]
This is simple documentation updates, so not sure what to update in the Changelog-Next file. Please advise!

**Comment by ebeahan** [comment]
Thanks, @nicpenning!

The asciidoc files are generated based on the schema definitions. Can you make your changes to [event.yml](https://github.com/elastic/ecs/blob/main/schemas/event.yml) and then run `make` to make the updates in the docs?

**Comment by nicpenning** [comment]
> Thanks, @nicpenning!
> 
> The asciidoc files are generated based on the schema definitions. Can you make your changes to [event.yml](https://github.com/elastic/ecs/blob/main/schemas/event.yml) and then run `make` to make the updates in the docs?

Good to know. I can do that!

**Comment by nicpenning** [comment]
I am trying to run `make` but I am seeing this error:
```
napsta@el33t-b00k-1:~/ecs$ make
make: build/ve/bin/pip: No such file or directory
make: *** [Makefile:107: build/ve/bin/activate] Error 127
```

I pulled directly from https://github.com/elastic/ecs.git about 10 minutes ago.

I don't see pip in ecs/build/ve/bin/pip, only python:
```
napsta@el33t-b00k-1:~/ecs$ ls build/ve/bin/
python  python3  python3.10
```

**Comment by ebeahan** [comment]
> I am trying to run make but I am seeing this error:

Looks like you were able to resolve the issue?

After running `make`, there will be a set of updated files to commit else the tests will continue to fail. These changes include all places to update with the changes made in `event.yml`.

```
$ git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   docs/fields/field-values.asciidoc
	modified:   experimental/generated/beats/fields.ecs.yml
	modified:   experimental/generated/csv/fields.csv
	modified:   experimental/generated/ecs/ecs_flat.yml
	modified:   experimental/generated/ecs/ecs_nested.yml
	modified:   generated/beats/fields.ecs.yml
	modified:   generated/csv/fields.csv
	modified:   generated/ecs/ecs_flat.yml
	modified:   generated/ecs/ecs_nested.yml
```

**Comment by nicpenning** [comment]
I was not able to resolve the issue.

I only updated the `event.yml` and committed just that effort.

I cannot run `make` since it's looking for `pip` in that `build/ve/bin` directory. I am not sure if that is something I need to set up or not.

**Comment by ebeahan** [comment]
In the root of the ECS repo on your machine, try:

```
$ rm -rf ./build
$ make ve
```

And then run `make` again.

`make ve` is included as part of the top-level `make` command, but let's separate it out in case there's something unexpected happening.

If the above steps are still not successful, can you confirm [using these steps](https://pip.pypa.io/en/stable/installation/#supported-methods) if `pip` is installed in the Python distribution you're using? If not, try running [`ensurepip`](https://pip.pypa.io/en/stable/installation/#ensurepip) to resolve.

**Comment by nicpenning** [comment]
I will give this s go as soon as I can

**Comment by nicpenning** [comment]
Your recommendation on removing the `build` directory and running `make` again, appeared to have worked!

```
napsta@el33t-b00k-1:~/ecs$ make
build/ve/bin/python scripts/generator.py --strict --include "" --subset "schemas/subsets/" --force-docs
Loading schemas from local files
Running generator. ECS version 8.10.0-dev
build/ve/bin/python --version
Python 3.10.6
build/ve/bin/python scripts/generator.py --include experimental/schemas --subset "schemas/subsets/" "experimental/schemas/subsets/" --out experimental
Loading schemas from local files
Running generator. ECS version 8.10.0-dev
Experimental ECS version 8.10.0-dev+exp
Loading user defined schemas: ['experimental/schemas']
```

Did I miss that step in the documentation to stand up my development environment?

**Comment by nicpenning** [comment]
New proper PR here: 2226

Closing this as a learning session :)

**Pull request closed without merging**
