### PR TITLE
registry.data.strings field missing array definition.

### LINKED ISSUE #776: [1.5] registry.data.strings field missing array definition?
It looks like re-running the ECS .NET generator has picked up a change to `registry.data.strings`.

In `1.4.0` it was manually overridden to emit a `string[]` type but is now emitting `string` type as the field has no normalize->array definition.

The description for this property reads as:

> Content when writing string types.<para/>Populated as an array when writing string data to the registry. For single string registry types (REG_SZ, REG_EXPAND_SZ), this should be an array with one string. For sequences of string with REG_MULTI_SZ, this array will be variable length. For numeric data, such as REG_DWORD and REG_QWORD, this should be populated with the decimal representation (e.g `"1"`).

https://github.com/elastic/ecs-dotnet/blob/8cfe5f6c5661427204e42891ede4d8fcc8889231/src/Elastic.CommonSchema/Types.Generated.cs#L3514

Should this be modelled as an array? I was also wondering if it would be equally valid for this to be a `Union<string[], decimal>`?

### PR DESCRIPTION
**Pull request by codebrain**
Fixes #776

Please re-run generator before approving, thanks!

### CODE REVIEW

**Comment by webmat** [comment]
Yes I agree, thanks for raising this :-)

I think the PR for Registry was being worked on at the same time as the normalize/array PR.

**Comment by webmat** [comment]
Generated files were fine. I simply added a bugfix changelog entry.

**Comment by webmat** [comment]
@codebrain Hey btw please clone the ECS repo, and create your branches & submit your PRs from your fork.

We need to limit the branches on the official repo to version branches and the occasional long term experimental branch. But no feature branches here, as much as possible. It creates too much of a mess :-)

**Comment by codebrain** [comment]
> @codebrain Hey btw please clone the ECS repo, and create your branches & submit your PRs from your fork.

No problem, will do in future.

**Pull request merged**
