### PR TITLE
Rename hostname to host.name fields to be consistent

### PR DESCRIPTION
**Pull request by ruflin**
`destination.hostname`, `device.hostname` and `source.hostname` were renamed to `*.host.name` to be consitent with the host object.

Related to https://github.com/elastic/ecs/issues/62

### CODE REVIEW

**Comment by webmat** [comment]
LGTM

**Comment by MikePaquette** [comment]
@ruflin I think "hostname" is a better ECS name for this field, as we are looking to populate this with the internet hostname which is commonly known as "hostname."  See [wikipedia hostname](https://en.wikipedia.org/wiki/Hostname).  

This too would preserve a consistent use of "hostname" in `source.hostname`, `destination.hostname`, and `device.hostname`.  But for consistency, this also means that we would have `host.hostname`, which has been criticized previously as being redundant, and could seem to run afoul of our _Avoid Repetition_ [naming guideline ](https://github.com/elastic/ecs/blob/master/README.md#guidelines). Nonetheless, since "hostname" is the actual name of the entity stored in the field, I think this justifies keeping it.

Also, in case we decide to keep `host.*` as a top-level namespace/object/prefix only, the use of "hostname" keeps us clear of conflicts.

Finally, this also allows us to continue to have only one dot in our commonly used "ECS-compatible" fields, an original ECS goal to assist with ease-of-recall and predictability. 

I vote for no further changes from `*.hostname` to `*.host.name` and for reverting `host.name` to `host.hostname` for consistency.

**Comment by ruflin** [comment]
Renaming `host.name` to `host.hostname` is an other way we could go. My current preference is still with `host.name` but it ties into the discussion here: https://github.com/elastic/ecs/issues/71 It would mean `hostname` is a reusable field.

**Comment by webmat** [comment]
Yeah I think I'm also in favor of sticking with the widely used naming, in cases like this.

**Comment by webmat** [comment]
As discussed, we're closing this and we'll be sticking with `hostname` instead.

**Comment by ruflin** [comment]
Would be good to add here a comment with reasoning so if we get back to it we know why.

**Pull request closed without merging**
