### PR TITLE
Add user details commonly seen in user management audit logs.

### PR DESCRIPTION
**Pull request by webmat**

### CODE REVIEW

**Comment by ruflin** [comment]
Not sure if we should put this into scope of ECS 1.0. Do we have these in the auditbeat already?

**Comment by webmat** [comment]
Yes these are fields we will see in any typical user auditing solution. There are more, but these 3 fields are the most obvious ones, IMO.

I haven't touched Filebeat's `auditd` mapping yet, but I saw a need for these in Filebeat's `system.auth` fileset ([useradd log](https://github.com/elastic/beats/pull/9138/files#diff-d89539fc1f780fc038a94210a3c70df5L143)).

**Comment by ruflin** [comment]
What about auditbeat?

**Comment by ebeahan** [comment]
This PR has been stale for a while, and we're going to close it.

**Pull request closed without merging**
