### PR TITLE
Add `Principles` docs section

### LINKED ISSUE #1675: [DOCS] ECS principles
Add a section to the docs that serves as a foundation and guide for ECS basics.

The following items are ideas collected from brainstorming. The first iteration likely won't contain all of these ideas.

* Capturing concepts that work across many sources
* Parent fields are namespaces
* Regularity between namespaces
* Various levels of adoption
* mechanics
    * break down event data and extract it into fields
    * add metadata to events
    * add static data (e.g., event categorization, identify the source)
* Expands some of the style and convention concepts introduced briefing in the docs `Using ECS` section.
* Avoid capturing general concept names for narrow use cases

### PR DESCRIPTION
**Pull request by ebeahan**
Introduces a new section in the ECS docs to better capture some foundational design and implementation concepts.

This new section has two subsections:

* **Design** - Considerations that form the basis of ECS.
* **Implementation Patterns** - A collection of common implementation patterns commonly used in practice but not well documented today.

[Docs preview](https://ecs_1703.docs-preview.app.elstc.co/guide/en/ecs/master/index.html)

Resolves #1675

### CODE REVIEW

**Comment by ebeahan** [comment]
This one's ready for review. Feel free to pull other folks into the discussion.

@djptek @kgeller @jamiehynds @epixa @MikePaquette

**Comment by ebeahan** [comment]
@kgeller, Appreciate the feedback!

> However I wonder about structuring. I hesitate about potential confusion between 'Principles' and 'Using ECS' and I wonder if they could be better combined somehow. The conventions described on the 'Implementation Patterns' feels similar to 'Guidelines and Best Practices'. And just the overall vibe of each section feels related.

I've had the same hesitation. Perhaps I place the design principles as a new section under `Using ECS` and merge `Implementation Patterns` with the existing guidelines/best practices doc. 🤔 

> Also a bit nit picky, but I like the Using ECS's intro page where it has a little guide kinda on where to go and I think the principles section could benefit from that over bullet points.

👍

**Comment by ebeahan** [comment]
The latest round of changes:

* Removed `Principles` section and folded all its content into `Using ECS.`
* `Guidelines and Best Practices` now contains three subsections:
    * `Conventions` - Relocated and reformatted, but content unchanged.
    *  `Implementation patterns` - Relocated and reformatted; Removed some unnecessary content with this new structure. 
    * `Mapping network events` - Relocated and reformatted, and content primarily unchanged. I think this spot is a logical place for the network event mapping doc with this new structure.
* Added `Design Principles` section underneath `Using ECS`

I hope by combining these new docs into `Using ECS,` everything feels more cohesive. I'm also open to other ideas about how we could structure.

**Comment by ebeahan** [comment]
I pushed the latest rounds of edits.

In good shape for another round of reviews when time allows.

**Review by kgeller — APPROVED** [review]
LGTM!

**Pull request merged**
