### PR TITLE
WIP add level (Core, Extended) on all fields.

### PR DESCRIPTION
**Pull request by webmat**
Subtasks:
- [x] Assign all fields either value
- [x] Remove all mentions of `phase`

This issue is only meant to cover assigning a level to the fields for #93. No modifications to the scripts in this PR.

### CODE REVIEW

**Comment by ruflin** [comment]
@webmat We could even split this up further. In a first PR only to the fields.yml modification and follow up with scripts etc. in parallel.

Let me know in case this is ready for review. It seems to have all the fields.yml changes inside?

**Comment by webmat** [comment]
@ruflin Yes that's true. I'll modify the scripts in a separate PR.

All fields should be assigned. If one is not, or if it's not == to the voting doc, it's a bug :-)

**Comment by MikePaquette** [comment]
LGTM. Thanks @webmat !

**Comment by webmat** [comment]
Thanks folks!

**Pull request merged**
