### PR TITLE
[RFC] Faas fields - stage 2

### PR DESCRIPTION
**Pull request by AlexanderWert**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)?
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)?
- If submitting code/script changes, have you verified all tests pass locally using `make test`?
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes?
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- Have you added an entry to the [CHANGELOG.next.md](https://github.com/elastic/ecs/blob/master/CHANGELOG.next.md)?

### CODE REVIEW

**Comment by kgeller** [comment]
@AlexanderWert This RFC is coming along nicely! Some questions:

1) New fields: I see `faas.trigger.request_id' and then `faas.execution`. If `execution` is simply going to be the id of the execution, any thoughts on renaming for consistency? Or is there potential other definitions not mentioned in the current description?

2) What do you see as the difference between the current `cloud.*` and the proposed `cloud.origin.*`?

**Comment by AlexanderWert** [comment]
@kgeller Thanks for your review!

> If `execution` is simply going to be the `id` of the execution, any thoughts on renaming for consistency?

`faas.execution` was inspired by the OpenTelemetry naming convention, and I think being aligned with [OpenTelemetry semantics](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/faas.md) when introducing new fields might be a good idea to not deviate too much. But I'd also be fine with `faas.execution_id` if it makes thinks clearer.

> What do you see as the difference between the current cloud.* and the proposed cloud.origin.*? And similarly service.* and service.origin.*?

This has already been discussed in the [stage-1 PR](https://github.com/elastic/ecs/pull/1542#discussion_r683308264) and documented in the concerns section of the RFC. I tried to clarify this aspect in the footnote descriptions in the `cloud.yml` and `service.yml` files in this PR. Do you think it helps understanding the difference better? Any other ideas how we can better clarify the difference?

**Comment by kgeller** [comment]
@AlexanderWert 

I think being consistent with OpenTelemetry is the right way to go.

Apologies for missing that info, I understand now. I do think the footnotes help! I was more concerned with the docs. What do you think about adding some of that context into a [usage doc](https://github.com/elastic/ecs/blob/master/docs/usage/README.md) ? We have one out there already for [user](https://www.elastic.co/guide/en/ecs/current/ecs-user-usage.html), and Eric is in the process of getting one added for [threat](https://github.com/elastic/ecs/pull/1597).

**Comment by AlexanderWert** [comment]
@kgeller 

I added now two docs in this PR (for cloud and service) on the usage of origin and target nesting.
Please, let me know if it goes in the direction you have in mind.

**Comment by kgeller** [comment]
@AlexanderWert I think those look awesome! Once the CI is all good, I think we are good to go!

**Comment by AlexanderWert** [comment]
@kgeller Seems like the CI fails because I added the docs:

```
...
./build/misspell/bin/misspell -error README.md CONTRIBUTING.md schemas/* docs/* experimental/schemas/*
# Check if diff is empty.
...
```

Was it wrong to add the docs directly under /docs/usage/ in this PR?
What do i need to do to fix that?
Thanks

**Comment by kgeller** [comment]
@AlexanderWert you did it perfectly! It just wants the updated version of the generated file `docs/field-details.asciidoc` , which you get just by running `make`.

**Comment by AlexanderWert** [comment]
@kgeller Thanks, that was an easy one :-). All green now.

**Comment by kgeller** [comment]
@AlexanderWert looks great! I will set the date and merge

**Review by kgeller — APPROVED** [review]

**Pull request merged**
