### PR TITLE
Add user.groups

### PR DESCRIPTION
**Pull request by webmat**
Question: singular or plural?

### CODE REVIEW

**Comment by ruflin** [comment]
I remember we had a discussion around this in the past. As in lucene single and multi values are the same, we should always stick to singular I think. For example `user.id` can also be a group but it's still not `user.ids`. So I would go with `user.group` but as in this case it can often be plural, mention in the description that it can also be a list.

**Comment by webmat** [comment]
@MikePaquette Does that make sense to you as well? `user.group` is singular, even if in some cases we will want to have multiple groups in this field.

**Comment by MikePaquette** [comment]
Yes @webmat singular makes sense, even if it might contain multiple value.  In ECS, we've been using plural only when the field "always" (or virtually aways) contains multiple.  (e.g. *.bytes).

**Comment by webmat** [comment]
Great! I'll rebase and merge, in this case.

**Pull request merged**
