### PR TITLE
[RFC] wip: data_stream - stage 2

### PR DESCRIPTION
**Pull request by roncohen**
Moving this to stage 2

[Preview the RFC](https://github.com/roncohen/ecs/blob/data_streams_stage_2/rfcs/text/0009-data_stream-fields.md)

### CODE REVIEW

**Comment by webmat** [comment]
Thanks for opening this @roncohen. Another quick initial change we can do here, is add this PR to the list of "RFC Pull Requests" at the end of the document.

**Comment by webmat** [comment]
@exekias Do you know who will take this one over for Ron?

**Comment by ruflin** [comment]
@webmat 🤚

**Comment by ruflin** [comment]
@webmat @ebeahan I updated the fields.yml. Anything else needed here?

**Comment by ebeahan** [comment]
Thanks, @ruflin, for taking over authorship and moving this forward!

Here's what I see as outstanding:

- [ ] An example source document or two in the `Source document` section. This proposal's additions are straight-forward, but it's a useful aid to demonstrate how the proposed fields are intended to be used.
- [ ] Identify the new RFC sponsor and capture in the `People` section.

**Comment by ruflin** [comment]
@ebeahan Updated, let me know if this works.

**Review by ebeahan — DISMISSED** [review]
LGTM 👍 

I'll adjust the advancement date prior to merging.

**Comment by ruflin** [comment]
@ebeahan Thanks for getting this in. By now there is also a blog post around this that we can reference / link in the future: https://www.elastic.co/blog/an-introduction-to-the-elastic-data-stream-naming-scheme Any next steps needs from my end?

**Comment by ebeahan** [comment]
@ruflin Thanks for sharing the blog post! I think it'd make a great addition to the proposal `References` section in the next stage.

Let's go ahead and open the next stage's PR, even if the only initial change is updating the stage from 2 to 3. We can use that PR to capture any concerns or feedback that arise.

**Comment by ruflin** [comment]
Done: https://github.com/elastic/ecs/pull/1212

**Pull request merged**
